#1

In [7]:
s="123456789"
l1=[]
for i in s:
    l1.append(i)
l1.reverse()
print(l1)


['9', '8', '7', '6', '5', '4', '3', '2', '1']


#2

In [10]:
s1 ,s2="hola caracola", "adios marieta"
l1=[]
for i in range(len(s1)):
    l1.append(s1[i])
    l1.append(s2[i])

print(l1)


['h', 'a', 'o', 'd', 'l', 'i', 'a', 'o', ' ', 's', 'c', ' ', 'a', 'm', 'r', 'a', 'a', 'r', 'c', 'i', 'o', 'e', 'l', 't', 'a', 'a']


#3

In [11]:
s="Hola me llamo Rafael"
l1=[]
for c in s:
    if c=="a" or c=="e" or c=="i" or c=="o" or c=="u" or c==" ":
        continue
    else:
        l1.append(c)

print(l1)


['H', 'l', 'm', 'l', 'l', 'm', 'R', 'f', 'l']


#4

In [43]:
s, l1, l1r="Aziza", [], []
s=s.lower()

for c in s:
    l1.append(c)
l1.reverse()
for tl in l1:
    l1r.append(tl)


l1.reverse()
if l1r==l1:
    print("{} es un palindromo.".format(l1))
else:
    print("{} no es un palindromo.".format(l1))

['a', 'z', 'i', 'z', 'a'] es un palindromo.


In [39]:
print(l1)
print()
print(l1r)

['a', 'n', 'i', 'n', 'a']

['a', 'n', 'i', 'n', 'a']


#5

In [66]:
import numpy as np

A , m=  np.matrix([[5.,2,3],[10,5,6],[88,88,91]]), []
print(A)
for fila in A:
    if fila[0,0] > fila[0,1]:
        if fila[0,0] > fila[0,2]:
            m.append(fila[0,0])
    elif fila[0,2]>fila[0,1]:
        if fila[0,2]>fila[0,0]:
            m.append(fila[0,2])
    else:
        m.append(fila[0,1])

print()
for i in range(len(m)):
    print("El maximo de la fila {} es {}".format(i+1,m[i]))


[[ 5.  2.  3.]
 [10.  5.  6.]
 [88. 88. 91.]]

El maximo de la fila 1 es 5.0
El maximo de la fila 2 es 10.0
El maximo de la fila 3 es 91.0


In [61]:
print(fila)
print(fila[0,1])

[[1 2 3]]
2


#6

In [72]:
n=int(input("Introduce el numero de filas (matriz nxn): "))
A=np.zeros((n,n))
k=0
for i in range(n):
    for j in range(n):
        A[i,j]=k
        k+=1
print(A)

    

Introduce el numero de filas (matriz nxn): 5
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]


#7

In [85]:
n=int(input("Introduce el numero de filas: "))
m=int(input("Introduce el numero de columnas: "))
A, sum, l, fla=np.empty((n,m)), 0. , [], 0


for i in range(n):
    for j in range(m):
        A[i,j]=float(input("Introduce el valor de la posicion ({},{}): ".format(i+1,j+1)))

print(A)

for j in range(m):
    sum=0.
    for i in range(n):
        sum+=A[i,j]
    l.append(sum)

for s in range(m):
    if s==(m-1):
        break
    if l[s] != l[s+1]:
        fla=1
        break

print("La suma de las columnas es diferente.") if fla == 1 else print("La suma de las columnas es igual a {}.".format(sum))


Introduce el numero de filas: 2
Introduce el numero de columnas: 4
Introduce el valor de la posicion (1,1): 1
Introduce el valor de la posicion (1,2): 1
Introduce el valor de la posicion (1,3): 1
Introduce el valor de la posicion (1,4): 1
Introduce el valor de la posicion (2,1): 1
Introduce el valor de la posicion (2,2): 1
Introduce el valor de la posicion (2,3): 1
Introduce el valor de la posicion (2,4): 1
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
La suma de las columnas es igual a 2.0.


#8

In [92]:
n=int(input("Introduce el numero de filas: "))
m=int(input("Introduce el numero de columnas: "))
A,fla=np.empty((n,m)) ,  0

if n==m:
    for i in range(n):
        for j in range(m):
            A[i,j]=float(input("Introduce el valor de la posicion ({},{}): ".format(i+1,j+1)))
            if i==j:
                if A[i,j]!=1:
                    fla=1
            else:
                if A[i,j]!=0:
                    fla=1
    print("La matriaz A no es una atriz identidad") if fla==1 else print("La matriz A es una matriz identidad.")
    print(A)

else:
    print("La matriz dada no es cuadrada.")

Introduce el numero de filas: 3
Introduce el numero de columnas: 3
Introduce el valor de la posicion (1,1): 1
Introduce el valor de la posicion (1,2): 0
Introduce el valor de la posicion (1,3): 0
Introduce el valor de la posicion (2,1): 0
Introduce el valor de la posicion (2,2): 1
Introduce el valor de la posicion (2,3): 0
Introduce el valor de la posicion (3,1): 0
Introduce el valor de la posicion (3,2): 0
Introduce el valor de la posicion (3,3): 1
La matriz A es una matriz identidad.
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#9

In [95]:
n=int(input("Introduce el numero de filas: "))
m=int(input("Introduce el numero de columnas: "))
A,At=np.empty((n,m)), np.empty((m,n)) 
for i in range(n):
    for j in range(m):
        A[i,j]=float(input("Introduce el valor de la posicion ({},{}): ".format(i+1,j+1)))
        At[j,i]=A[i,j]

print("Matriz A")
print(A)
print("MAtriz transpuesta")
print(At)

Introduce el numero de filas: 2
Introduce el numero de columnas: 3
Introduce el valor de la posicion (1,1): 1
Introduce el valor de la posicion (1,2): 2
Introduce el valor de la posicion (1,3): 6
Introduce el valor de la posicion (2,1): 7
Introduce el valor de la posicion (2,2): 9
Introduce el valor de la posicion (2,3): 5
Matriz A
[[1. 2. 6.]
 [7. 9. 5.]]
MAtriz transpuesta
[[1. 7.]
 [2. 9.]
 [6. 5.]]


#10

In [101]:
n=int(input("Introduce el numero de filas (matriz nxn): "))
A=np.zeros((n,n))
for i in range(n):
    for j in range(n):
        if i==j:
            A[i,j]=1
        else:
            A[i,j]=0
print("Matriz identidad de dimention {}x{}".format(n,n))
print(A)

Introduce el numero de filas (matriz nxn): 5
Matriz identidad de dimention 5x5
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
