In [13]:
import numpy as np

In [141]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
print("Shape ori: {}\nDim ori: {}".format(a.shape, a.ndim))
b = a.reshape(3,1,3)
print("Shape aft: {}\nDim aft: {}".format(b.shape, b.ndim))
print("Array original: {}\nArray 3D:\n{}".format(a,b))

Shape ori: (9,)
Dim ori: 1
Shape aft: (3, 1, 3)
Dim aft: 3
Array original: [1 2 3 4 5 6 7 8 9]
Array 3D:
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [ ]:
a =  np.array([[-6, -5], [-4, -3], [-2, -1]])
b = np.array([[1, 2], [3, 4], [5, 6]])

c = np.concatenate((b,a), axis = 1)
print(c)

In [ ]:
a = np.array([[1, 2, 3], [-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]])
b = np.array_split(a,3)
print(b)

In [ ]:
def confpalindromo(s):
    """
    Funcion que comprueba si una palabra es un palindromo
    arg: s - palabra 
    return: True si es un palindromo, false si no es palindromo
    
    """ 
    s=s.lower()
    lword, lwordrev = [], [] 
    for i in range(0,len(s)):
        lword.append(s[i])
        lwordrev.append(s[(i*-1)-1])
    resl=lword == lwordrev

    return resl


words = np.array([["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato",
"elle"]])

ispalindromo = np.frompyfunc(confpalindromo, 1,1)
ispalindromo(words)


array([[True, False, False],
       [False, True, False],
       [False, False, True]], dtype=object)

In [ ]:
a = np.array(["cena", "frío", "kayak", "remo", "sol"])
b = np.searchsorted(a,"python")
print(b)

3


In [1]:
from numpy import random as rd

In [137]:
n , a= rd.randint(1,11), int(input("Introduce un numeroentre el 1-10: "))

while a != n:
    print("¡Has fallado! ¡Prueba otra vez!")
    a= int(input("Introduce un numeroentre el 1-10: "))
else:
    print("¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el ",n)

Introduce un numeroentre el 1-10: 5
¡Has fallado! ¡Prueba otra vez!
Introduce un numeroentre el 1-10: 6
¡Has fallado! ¡Prueba otra vez!
Introduce un numeroentre el 1-10: 3
¡Has fallado! ¡Prueba otra vez!
Introduce un numeroentre el 1-10: 1
¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el  1


In [114]:
def acer(am,n):
    amn = []
    for i in range(0,5):
        if am[i] in amn:
            continue
        else:
            amn.append(am[i])
    amn = np.array(amn)
    count = 0
    for e in amn:
        if e in n:
            if len( n[n == e]) >= len( am[am == e]):
                count += len(am[am == e])
            else:
                count += len(n[n == e])
    return count



n = rd.randint(1,21, size=5)
print(n)
a = []
for _ in range(0,5):
    ae = int(input("Introduce un numeroentre el 1-20: "))
    a.append(ae)
am = np.array(a)
print(am)



wcom = [len(np.where(n == am)[0]), acer(am,n) ]

while wcom != [5,5]:
    print("Vuelve a intentarlo")
    print("Numeros acertados: {}\nNumero bien colocados: {}".format( wcom[1], wcom[0] ))
    a = []
    for _ in range(0,5):
        ae = int(input("Introduce un numeroentre el 1-20: "))
        a.append(ae)
    am = np.array(a)
    print(am)
    wcom = [len(np.where(n == am)[0]), acer(am,n)]
else:
    print("¡¡¡ENHORABUENA!!! Has acertado el array que había pensado: ",n )



[12  9  9  3  2]
Introduce un numeroentre el 1-20: 2
Introduce un numeroentre el 1-20: 6
Introduce un numeroentre el 1-20: 9
Introduce un numeroentre el 1-20: 12
Introduce un numeroentre el 1-20: 8
[ 2  6  9 12  8]
[1, 3]
Vuelve a intentarlo
Numeros acertados: 3
Numero bien colocados: 1
Introduce un numeroentre el 1-20: 12
Introduce un numeroentre el 1-20: 9
Introduce un numeroentre el 1-20: 9
Introduce un numeroentre el 1-20: 6
Introduce un numeroentre el 1-20: 2
[12  9  9  6  2]
[4, 4]
Vuelve a intentarlo
Numeros acertados: 4
Numero bien colocados: 4
Introduce un numeroentre el 1-20: 9
Introduce un numeroentre el 1-20: 9
Introduce un numeroentre el 1-20: 9
Introduce un numeroentre el 1-20: 12
Introduce un numeroentre el 1-20: 2
[ 9  9  9 12  2]
[3, 4]
Vuelve a intentarlo
Numeros acertados: 4
Numero bien colocados: 3
Introduce un numeroentre el 1-20: 9
Introduce un numeroentre el 1-20: 1
Introduce un numeroentre el 1-20: 1
Introduce un numeroentre el 1-20: 1
Introduce un numeroentre e

In [117]:
l = [-3, -2, -1, 0, 1, 2, 3]
a = rd.choice(l, size=(3,4))
b = rd.choice(l, size=(3,4))
print(a)
print(b)
print(np.add(a,b))

[[ 0  0 -1  1]
 [-3 -1  1 -2]
 [ 2  3  3  1]]
[[-3  3  3 -1]
 [-3  1  0  0]
 [-1 -2 -2  2]]
[[-3  3  2  0]
 [-6  0  1 -2]
 [ 1  1  1  3]]


In [125]:
def numvoc(s):
    s=s.lower()
    ls=s.split(" ")
    sf=ls[0]
    return sf.count("a")+sf.count("e")+sf.count("i")+sf.count("o")+sf.count("u")
num_voc = np.frompyfunc(numvoc,1,1)
words = np.array([["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato",
"elle"]])
print(num_voc(words))

[[2 1 2]
 [2 2 2]
 [2 2 2]]


In [135]:
def str_in_set(s,conj):
    return s in conj

str_in_set_array = np.frompyfunc(str_in_set,2,1)
words = np.array([["avion", "gato", "arroz"], ["cena", "kayak", "raton"], ["pluma", "perro",
"ellos"]])
conj = {"ala", "delfin", "arroz","cena", "kayak", "picnic","hoja", "gato","elle"}
print(str_in_set_array(words,conj))

[[False True True]
 [True True False]
 [False False False]]
